name: Pull the list of Open Watcom V2 releases and update the list in repo.

on:
  workflow_dispatch:


jobs:
  pull-releases:
    runs-on: ubuntu-latest

    permissions:
      contents: write
 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

        # Very hackish approach to see if the image needs to be rebuilt.
      - run: |
         curl -IL https://github.com/open-watcom/open-watcom-v2/releases/download/Current-build/ow-snapshot.tar.xz | grep etag > watcom-release-etag
         
         git config --global user.email "polling-bot@thenextbug.com"
         git config --global user.name "polling-bot"

         git checkout master 
         git diff --quiet || (git add watcom-release-etag && git commit -m "New Open Watcom build." )
         git push



