name: Pull the list of Open Watcom V2 releases and update the list in repo.

on:
  workflow_dispatch:


jobs:
  pull-releases:
    runs-on: ubuntu-latest

    permissions:
      contents: write
 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - uses: github-actions-tools/gh-list-releases@main
        id: list-releases
        with:
          owner: open-watcom 
          repo: open-watcom-v2 
          nb_results: 10
          prerelease: true

      - run: |
          echo '${{ steps.list-releases.outputs.releases_body }}' | jq -r '.[]' | while read release ; do 
            echo "release: ${release}"
          done



