name: Pull the list of Open Watcom V2 releases and update the list in repo.

on:
  workflow_dispatch:
  schedule:
    - cron: 30 6 * * 6 

jobs:
  pullReleases:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    outputs:
      toBuild: ${{ fromJson(steps.releases.outputs.to_build) }}
 
    steps:
      - name: Check out the repo
        uses: actions/checkout@v4

      - id: releases 
        run: prep.py

      - run: |  
          git config --global user.email "polling-bot@thenextbug.com"
          git config --global user.name "polling-bot"
          git add . && git commit -m "Updating seen release list."
          git push

  buildImage:
    needs: pullReleases
    #uses: ./.github/workflows/build-image.yml
    strategy:
      matrix:
        toBuild: ${{ needs.pullReleases.outputs.toBuild }}

    steps:
      - run: echo ${{ matrix.toBuild }}
      


